# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: eloston.ungoogled-chromium
PackageVersion: 154.0.8037.92
InstallerLocale: en-US
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_x86.exe
  InstallerSha256: ACDF7935EE75F020FC7504A4B8F6820A02B2898B1786D9AA3FB25C6BF319A7D8
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_x86.exe
  InstallerSha256: ACDF7935EE75F020FC7504A4B8F6820A02B2898B1786D9AA3FB25C6BF319A7D8
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.92-1.1_windows_x86/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_windows_x86.zip
  InstallerSha256: 188518967BCE65EC84BFEF4A24A41E22F26D74B874EFCFE777FD507AB73F2B2A
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_x64.exe
  InstallerSha256: C55C95C49BA1D010FBD0A1C8F8AEF13585A175BA818CB1DB10A152294AB9CB60
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_x64.exe
  InstallerSha256: C55C95C49BA1D010FBD0A1C8F8AEF13585A175BA818CB1DB10A152294AB9CB60
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.92-1.1_windows_x64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_windows_x64.zip
  InstallerSha256: B50A2A1F50BEE804BDA42EEC434F4BA985DCCDA96A8122447104581C1768858D
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_arm64.exe
  InstallerSha256: 186681DB87F092C4743D462FB56AB7BB4AA394CFA352DD5192E96B6BA81B7A2E
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_installer_arm64.exe
  InstallerSha256: 186681DB87F092C4743D462FB56AB7BB4AA394CFA352DD5192E96B6BA81B7A2E
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.92-1.1_windows_arm64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.92-1.1/ungoogled-chromium_154.0.8037.92-1.1_windows_arm64.zip
  InstallerSha256: 981191877B90894F6A575EA9E49B3032D7BF6A0BE4CFCC70FEC1BF67C66241E8
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
