# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: eloston.ungoogled-chromium
PackageVersion: 154.0.8037.97
InstallerLocale: en-US
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_x86.exe
  InstallerSha256: 18078D3803CE902C553DDA383134DB8E3A869E45615ED69ACF4D5B01061F8E23
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_x86.exe
  InstallerSha256: 18078D3803CE902C553DDA383134DB8E3A869E45615ED69ACF4D5B01061F8E23
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.97-1.1_windows_x86/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_windows_x86.zip
  InstallerSha256: 2248C14AA4999313C954B173324D32F66FE1400E6EE0B2F39AD2B75C89302BC9
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_x64.exe
  InstallerSha256: FFA3F05B7C7039259F524B180788FCA729CEA1FA23D5B9AC12E63195B2F81802
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_x64.exe
  InstallerSha256: FFA3F05B7C7039259F524B180788FCA729CEA1FA23D5B9AC12E63195B2F81802
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.97-1.1_windows_x64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_windows_x64.zip
  InstallerSha256: 1B57760D04B557ECE1AF3271BC62141B3E6656DBD16EE536F8CE0A27103FD3C2
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_arm64.exe
  InstallerSha256: B86F3A1265C84AFC3D8E177CA612B260024CECDDDA0B41BCEAE5436AE350E7D4
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_installer_arm64.exe
  InstallerSha256: B86F3A1265C84AFC3D8E177CA612B260024CECDDDA0B41BCEAE5436AE350E7D4
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.97-1.1_windows_arm64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.97-1.1/ungoogled-chromium_154.0.8037.97-1.1_windows_arm64.zip
  InstallerSha256: 0CB9002258329FD0A0C60E3940B036AEDE96A2FEF412521AE2D565858B09DCF5
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
