# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: eloston.ungoogled-chromium
PackageVersion: 154.0.8037.57
InstallerLocale: en-US
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_x86.exe
  InstallerSha256: 2B9ADE9B889AC1EC71930CC93189A5328E492736467580214B72D57E56FACE7F
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_x86.exe
  InstallerSha256: 2B9ADE9B889AC1EC71930CC93189A5328E492736467580214B72D57E56FACE7F
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.57-1.1_windows_x86/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_windows_x86.zip
  InstallerSha256: 28084443E7D4941335C4A3D43433D48D51BAFCD4FF9B1B580024908E740D7606
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_x64.exe
  InstallerSha256: 17E14AF2C76E3D275CA4D49D6B58D5FE69DFEA2600CE736190D65B8BC5D54AFC
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_x64.exe
  InstallerSha256: 17E14AF2C76E3D275CA4D49D6B58D5FE69DFEA2600CE736190D65B8BC5D54AFC
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.57-1.1_windows_x64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_windows_x64.zip
  InstallerSha256: D4B8F53E8100E428A6CCEA8070A1A909AF3022C21070BFCD7DCA102990D95D88
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_arm64.exe
  InstallerSha256: 1AD86E0D8BE07BC4CE8AE43BEBA1AB355508B643AC5BCA32A81B20B852AEA10C
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_installer_arm64.exe
  InstallerSha256: 1AD86E0D8BE07BC4CE8AE43BEBA1AB355508B643AC5BCA32A81B20B852AEA10C
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_154.0.8037.57-1.1_windows_arm64/chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/154.0.8037.57-1.1/ungoogled-chromium_154.0.8037.57-1.1_windows_arm64.zip
  InstallerSha256: AAA58A781D9718A69708209DBD028385B370E5B99DA7CF0A8F4E3BAD12E5711A
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
